CONFIG += c++11
SOURCES += main.cc
QT += core

QMAKE_CXXFLAGS += -fopenmp
LIBS += -fopenmp

QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE *= -O3
QMAKE_CXXFLAGS_RELEASE *= -march=native
QMAKE_LFLAGS_RELEASE -= -Wl,-O1
QMAKE_LFLAGS_RELEASE *= -O3
